name: Gen metadata files

on: [push]
        
jobs:
  gen-metadata:
    name: Gen metadata
    concurrency: ci-metadata
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyarrow
        
    - name: Authentication
      env:
        QS_TOKEN: ${{ secrets.QUANTUM_SERVICES_TOKEN }}
      run: |
        python workflow.py authentication --channel="ibm_quantum" --token="${QS_TOKEN}" --instance="ibm-q/open/main"
    - name: Generate metadata
      env:
        CIRCUIT_ID: '18'
        SHOTS: '1024'
        MATRIX_SIZE: '200'
        NB_QUBITS: '4'
        LAYER: '2'
        BACKEND: 'ibmq_qasm_simulator'
      run: |
        echo "::notice file=resources/kernel_metadata/telemetry_info.csv::Circuit ${CIRCUIT_ID} ; Matrix size ${MATRIX_SIZE}"
        python workflow.py kernel_flow --circuit_tpl_id=[${CIRCUIT_ID}] --width=${NB_QUBITS} --layer=${LAYER} --matrix_size=[${MATRIX_SIZE},${MATRIX_SIZE}] --backend="${BACKEND}" --shots=${SHOTS}
        
    - name: Pull modif
      run: git pull
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automation gen metadata files
