name: Update Studies

on:
  workflow_dispatch:
  push:
    paths:
      - 'resources/**'
  
jobs:
  notebook_update:
    name: Regen jupyter notebook
    concurrency: ci-studies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r studies/requirements.txt
        
    - name: Update analysis notebook
      run: |
        python -m pip install jupyter nbconvert nbformat
        jupyter nbconvert --to notebook --execute studies/telemetry_analyser.ipynb --inplace
    
    - name: Pull modif
      run: git pull
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automation gen metadata files
